model: 
  path: '/Users/jrmylee/Documents/Development/projects/mir/repos/BTC-ISMIR19'
  feature_size : 108
  timestep : 108
  num_chords : 133
  input_dropout : 0.2
  layer_dropout : 0.2
  attention_dropout : 0.2
  relu_dropout : 0.2
  num_layers : 8
  num_heads : 4
  hidden_size : 128
  total_key_depth : 128
  total_value_depth : 128
  filter_size : 128
  loss : 'ce'
  probs_out : False
  sample_rate: 22050
preprocess:
  sample_rate: 22050
  hop_size: 2048
  window_size: 10
  song_hz: 22050